### ISSUE TITLE
Close v-show.lazy component by itself leads to an error

### ISSUE THREAD

**Issue by jaufey** [antfu/v-lazy-show#6]
### Describe the bug

Binding a custom event handler on the same component that has v-lazy-show for closing gives an error:
`[plugin:vite:vue] Cannot read properties of undefined (reading 'trim')`

### Reproduction

https://stackblitz.com/edit/vitejs-vite-3cpoq2?file=src%2FApp.vue,src%2FChild.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    Memory: 5.21 GB / 15.89 GB
  Binaries:
    Node: 18.16.0 - D:\nodejs\node.EXE
    npm: 9.5.1 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nigiwen** [comment]
You need to wrap it inside a div
https://stackblitz.com/edit/vitejs-vite-rjq1dhhq?file=src%2FApp.vue
