### ISSUE TITLE
Bug: broken with vue <3.4.21 in nuxt project

### ISSUE THREAD

**Issue by webfansplz** [antfu/v-lazy-show#9]
### Describe the bug

![image](https://github.com/antfu/v-lazy-show/assets/22515951/371a5d37-27db-4be4-b04e-d342b2eba254)
![image](https://github.com/antfu/v-lazy-show/assets/22515951/253cdb07-f72d-4497-b2a7-2162b23d6d15)

### Reproduction

(3.4.20 - work failed) https://stackblitz.com/edit/nuxt-starter-pvmtms?file=package.json,nuxt.config.ts,app.vue
(3.4.21 - work fine) https://stackblitz.com/edit/nuxt-starter-jnm8te?file=app.vue 

### System Info

```Shell
Reproduction step:

1. upgrade Vue to 3.4.20 in v-lazy-show repo 

2. start the Nuxt playground


```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's more like a bug of 3.4.20 I believe. It works with the latest version.
